### ISSUE TITLE
Command - notify

### ISSUE THREAD

**Issue by TheRealDannyyy** [Armaldio/alfred-botler#10]

**Comment by TheRealDannyyy** [comment]
Unknown template, which one do you mean?

**Comment by Armaldio** [comment]
There is none, need new one

This command is used in case someone need to take action on his own
messages

- user post in wrong Chan
- put a notification asking him to move
  Notification have an OK emoji that needs to be hit to delete itself and
notify the notification poster that user have taken action

Le jeu. 10 janv. 2019 à 12:52, TheRealDannyyy <notifications@github.com> a
écrit :

**Comment by TheRealDannyyy** [comment]
Is this automated based on an detection pattern?

**Comment by Armaldio** [comment]
What?

Le jeu. 10 janv. 2019 à 13:15, TheRealDannyyy <notifications@github.com> a
écrit :

**Comment by Armaldio** [comment]
The only thing that is manual is the `!notify #message#` command

**Comment by TheRealDannyyy** [comment]
So this is another step before moving the messages? Some sort of warning?

**Comment by Armaldio** [comment]
This is to let the use doing it by himself
And its not only applicable to moving message, its for any sort of
notification

More like a "message from the staff" instead of of you posting the message
in your name. So there is no favoritisme over one mod or an other

Le jeu. 10 janv. 2019 à 14:35, TheRealDannyyy <notifications@github.com> a
écrit :

**Comment by TheRealDannyyy** [comment]
What's the difference between this command and the old channel specific !say command?

**Comment by Armaldio** [comment]
The ability to autodelete the message on task completion and to keep track
of that completion by the author

Le jeu. 10 janv. 2019 à 15:19, TheRealDannyyy <notifications@github.com> a
écrit :

**Comment by TheRealDannyyy** [comment]
How would a custom template of this look like?

**Comment by Armaldio** [comment]
[image: image.png]
```json
{
  "embed": {
    "title": "YOU ARE REQUIRED TO TAKE ACTION",
    "description": "@someone1, @someone2\n\nSome of these messages does not
belong to this channel, please move them!",
    "color": 16738628,
    "footer": {
      "text": "Please hit the OK button at the bottom of this message to
let us know you've successfully done the required action"
    },
    "thumbnail": {
      "url": "
https://raw.githubusercontent.com/Armaldio/alfred-botler/master/assets/mini/Infoicon.png
"
    }
  }
}
```

Le ven. 11 janv. 2019 à 11:07, TheRealDannyyy <notifications@github.com> a
écrit :

**Comment by TheRealDannyyy** [comment]
Alright, I get it now.

**Comment by TheRealDannyyy** [comment]
Pushed out basic template with two customizable fields. 

How to add content to those fields, needs to be figured out. 
I assume a step by step process in private is the way to go:
1. !notify
2. Ask for headline
3. Ask for reason
