### ISSUE TITLE
Command - status

### ISSUE THREAD

**Issue by TheRealDannyyy** [Armaldio/alfred-botler#13]

**Comment by TheRealDannyyy** [comment]
Unknown template, which one do you mean?

**Comment by Armaldio** [comment]
That was a command to display infos about the bot like basic stats and
uptimes

Is it still needed?

Le jeu. 10 janv. 2019 à 11:48, TheRealDannyyy <notifications@github.com> a
écrit :

**Comment by TheRealDannyyy** [comment]
oh the status thing. I would keep it, since it could be useful sometimes.

**Comment by TheRealDannyyy** [comment]
Meh, I will remove this as well. No one except me used it anyway.
