### ISSUE TITLE
Command - help

### ISSUE THREAD

**Issue by TheRealDannyyy** [Armaldio/alfred-botler#14]

**Comment by TheRealDannyyy** [comment]
Unknown template, which one do you mean?

**Comment by Armaldio** [comment]
I think that was the old !notice command.
Unneeded now

Le jeu. 10 janv. 2019 à 11:48, TheRealDannyyy <notifications@github.com> a
écrit :

**Comment by TheRealDannyyy** [comment]
I have a help template, this one is a template that's being posted via PM when someone types !help.

**Comment by TheRealDannyyy** [comment]
![image](https://user-images.githubusercontent.com/15656049/50984001-097f5080-1501-11e9-8e1a-4aa1233a2b35.png)

**Comment by Armaldio** [comment]
Yes. Is it still needed?

Le jeu. 10 janv. 2019 à 11:56, TheRealDannyyy <notifications@github.com> a
écrit :

**Comment by Armaldio** [comment]
Not sure

Le jeu. 10 janv. 2019 à 12:23, TheRealDannyyy <notifications@github.com> a
écrit :

**Comment by TheRealDannyyy** [comment]
We can remove it either way. I don't remember this being used that often.
