### ISSUE TITLE
Command - removepromo

### ISSUE THREAD

**Issue by TheRealDannyyy** [Armaldio/alfred-botler#15]
Usage proposal:
1. Post `!promodel` followed by message ID
2. Post template if successful as private message [#user# An error as occurred! Please try again later or report to staff!]

**Comment by TheRealDannyyy** [comment]
Need new template, can't find old one.

**Comment by Armaldio** [comment]
Are you sure it's needed. I've seen usage of this only 1 time.
If people want to remove, just contact us.

**Comment by TheRealDannyyy** [comment]
Up to you really, just did a copypaste.

**Comment by TheRealDannyyy** [comment]
Removed based on previous comment as reason.
