### ISSUE TITLE
BlogPosts checks

### ISSUE THREAD

**Issue by TheRealDannyyy** [Armaldio/alfred-botler#21]

**Comment by Armaldio** [comment]
@TheRealDannyyy Template needed

**Comment by TheRealDannyyy** [comment]
The *here* tag is missing.

Does it also post community blogposts inside the community channel?

**Comment by Armaldio** [comment]
Yes scirra staff in scirra announcement, otherwise
Community
Will do a separate task for @here tag

Le jeu. 10 janv. 2019 à 18:51, TheRealDannyyy <notifications@github.com> a
écrit :

**Comment by TheRealDannyyy** [comment]
Referenced since this is more of a global issue.
