### ISSUE TITLE
Prevent bots from spamming NSFW content 

### ISSUE THREAD

**Issue by Armaldio** [Armaldio/alfred-botler#32]

**Comment by TheRealDannyyy** [comment]
Possible solutions:
- Remove public list bots (reset invites, use 1 global invite only)
- Remove join message limit and replace with bot limit (new users links don't embed for 10min.)
- Consent channel, full access requirement

**Comment by Armaldio** [comment]
Current solution in test: message is censored if:
- Contain blacklisted words
- Author joined less than 24h

A duplicate of the censored message is posted in #bin channel and reasons are sent to the author of the message via DM.

**Comment by TheRealDannyyy** [comment]
What blacklist?

**Comment by Armaldio** [comment]
https://github.com/Armaldio/alfred-botler/blob/master/bot-utils.js#L57
