### ISSUE TITLE
Bot errors shouldn't send reason in PM

### ISSUE THREAD

**Issue by TheRealDannyyy** [Armaldio/alfred-botler#35]
Any critical error messages should be included inside the initial error message, stating that an error as occurred.

**Comment by Armaldio** [comment]
I don't get it. When you got the error, you also got a PM?

Le lun. 14 janv. 2019 à 17:53, TheRealDannyyy <notifications@github.com> a
écrit :

**Comment by Armaldio** [comment]
Weird

Le lun. 14 janv. 2019 à 18:28, TheRealDannyyy <notifications@github.com> a
écrit :
