### ISSUE TITLE
Occasional !say command issues

### ISSUE THREAD

**Issue by TheRealDannyyy** [Armaldio/alfred-botler#36]
![image](https://user-images.githubusercontent.com/15656049/51197147-fe596580-18f0-11e9-8d65-d67900988645.png)

**Comment by TheRealDannyyy** [comment]
It happens at random. I literally posted the same template 2min later, without any errors.

**Comment by Armaldio** [comment]
Ah, got it.
Not a real error. 

Once I have the bot launched + my local version running, both bots want to remove the original command message. But once the message is deleted, the second bot cannot delete it since it doesn't exit anymore, saying that the said message is an `Unknown message`
