### ISSUE TITLE
Command - report

### ISSUE THREAD

**Issue by TheRealDannyyy** [Armaldio/alfred-botler#9]

**Comment by TheRealDannyyy** [comment]
This could also be simplified.

If a user uses "!report". Post a message inside the moderators channel that a review is required and post the most recent messages (e.g. 25) into the bin channel, for reference.

**Comment by Armaldio** [comment]
Is a template required in the channel where the command is used ?

**Comment by TheRealDannyyy** [comment]
No Templates.
